name: OWASP Dependency Check
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Priming build with Maven
        run: mvn clean install -DskipTests
      - name: Dependency Check
        run: mvn org.owasp:dependency-check-maven:aggregate
      - name: Cleanup snapshots cache
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
      - name: Archive Check Reports
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          retention-days: 7
          path: |
            **/target/dependency-check-report.html
